# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C_z8OUwjBYJ_d6nHa5247PUFSSiapb_6
"""

from flask_sqlalchemy import SQLAlchemy
from flask import Flask

# Initialize Flask app and configure database
app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///insurance_recommendations.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)

# Define database models
class CustomerProfile(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    age = db.Column(db.Integer, nullable=False)
    smoker = db.Column(db.Boolean, nullable=False)
    claim_amount = db.Column(db.Float, nullable=False)
    recommendations = db.relationship('Recommendation', backref='customer', lazy=True)

class Recommendation(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    product_id = db.Column(db.Integer, nullable=False)
    customer_id = db.Column(db.Integer, db.ForeignKey('customer_profile.id'), nullable=False)

# Create database tables
with app.app_context():
    db.create_all()